name: Docker Build Validation
on:
    pull_request:
        branches:
            - main
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: |
               docker build -t portfolio .