name: Publish Image to ECR
on:
    release:
        types: [published]
jobs:
    Publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{secrets.AWS_ECR_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_ECR_SECRET_ACCESS_KEY}}
                aws-region: ${{secrets.AWS_REGION}}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, Tag and push Image
              env:
                REGISTRY: ${{steps.login-ecr.outputs.registry}}
                REPOSITORY: ${{secrets.ECR_REPOSITORY}}
                IMAGE_TAG: ${{github.event.release.tag_name}}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest

                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
                docker push $REGISTRY/$REPOSITORY:latest