name: Release Image
on:
    release:
        types: [published]
jobs:
    Release_Image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN }}

            - name: Build and Push Versioned Image
              run: |
               VERSION=${GITHUB_REF#refs/tags/}

               docker build \
                 -t ghcr.io/${{github.repository_owner}}/portfolio-devops-project:$VERSION \
                 -t ghcr.io/${{github.repository_owner}}/portfolio-devops-porject:latest \
                 .
                 
               docker push ghcr.io/${{github.repository_owner}}/portfolio-devops-project:$VERSION
               docker push ghcr.io/${{github.repository_owner}}/portfolio-devops-project:latest
